service: projectify-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  # profile: serverless-envision
  region: ap-south-1
  stage: dev
  environment: 
    JWT_SECRET: ${self:custom.jwt_secret}
    ENV: ${self:provider.stage}

package:
  individually: true

custom:
  jwt_secret: projectify-backend-developed-by-divyanshu-kaushik-jwt-secret

functions:
  server:
    handler: ./src/app.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true